//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_Signature
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_key
    {
        public tbl_key()
        {
            this.tbl_user = new HashSet<tbl_user>();
        }
    
        public int sig_id { get; set; }
        public string private_key { get; set; }
        public int public_key { get; set; }
        public int n { get; set; }
        public int user_id { get; set; }
    
        public virtual ICollection<tbl_user> tbl_user { get; set; }
    }
}
